name: CI
on: [pull_request]
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: '2.7' }
          - { ruby: '3.0' }
          - { ruby: '3.1' }
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
